on:
  push:
    branches:
      - master
    paths:
      - pubspec.yaml
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  contents: write  # Allow the GitHub Actions bot to write to the repository

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # Replace with your Flutter version

      - name: Bump version
        id: bump_version
        run: |
          current_version=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          IFS="." read -r major minor patch <<< "$current_version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          sed -i "s/version: .*/version: $new_version/" pubspec.yaml
          echo "::set-output name=version::$new_version"

      - name: Commit version bump
        run: |
          git config --local user.email "lagger543@gmail.com"  # Set your email
          git config --local user.name "BlacKruk"  # Set your username
          git add pubspec.yaml
          git commit -m "Bump version to ${{ steps.bump_version.outputs.version }}" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/BlacKruk/Flutter.git master
